// Generated by CoffeeScript 1.6.0
var EquationOfTime, d, eot, eotValue, longitude, timenet;

EquationOfTime = (function() {

  function EquationOfTime(date) {
    this.init(date);
  }

  EquationOfTime.prototype.W = function() {
    return 360 / 365.24;
  };

  EquationOfTime.prototype.init = function(date) {
    var now;
    now = new Date();
    now.setHours(0);
    now.setMinutes(0);
    now.setSeconds(0);
    now.setDate(1);
    now.setMonth(0);
    return this.D = Math.floor((date.getTime() - now.getTime()) / 86400000);
  };

  EquationOfTime.prototype.A = function() {
    return this.W() * (this.D + 10);
  };

  EquationOfTime.prototype.B = function() {
    return this.A() + 360 / Math.PI * 0.0167 * Math.sin(this.W() * (this.D - 2));
  };

  EquationOfTime.prototype.C = function() {
    return (this.A() - Math.atan(Math.tan(this.B()) / Math.cos(23.44))) / 180;
  };

  EquationOfTime.prototype.EOT = function() {
    var C;
    C = this.C();
    return 720 * (C - Math.round(C));
  };

  EquationOfTime.prototype.Declination = function() {
    return 0 - (Math.asin(Math.sin(23.44) * Math.cos(this.B())));
  };

  return EquationOfTime;

})();

if (process.argv[2]) {
  longitude = parseFloat(process.argv[2]);
} else {
  longitude = 0;
}

if (process.argv[3]) {
  timenet = parseFloat(process.argv[3]);
} else {
  timenet = 0;
}

d = new Date();

eot = new EquationOfTime(d);

console.log("W: " + (eot.W()));

console.log("A: " + (eot.A()));

console.log("B: " + (eot.B()));

console.log("C: " + (eot.C()));

eotValue = eot.EOT();

console.log("EOT: " + eotValue);

console.log("EOT+longitude: " + (eotValue + longitude - timenet));

console.log("Declination: " + (eot.Declination()));
